version: "3.3"
services:
  chirpstackagent:
    image: marcdespland/chirpstack-ngsiagent:1.0.0
    environment:
      - ORION_API_URL=http://proxyld:8080
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  decoderagent:
    image: marcdespland/decoder-ngsiagent:1.1.0
    environment:
      - "ORION_API_URL=http://proxyld:8080"
      - "MQTT_URL=mqtt://mosquitto:1883"
      - "DEVICE_LIST={\"urn:ngsi-ld:AirQualityObserved:Co2:sensor1\": \"urn:ngsi-ld:Device:chirpstack:0004a30b001f3423\", \"urn:ngsi-ld:AirQualityObserved:Co2:sensor2\": \"urn:ngsi-ld:Device:chirpstack:0004a30b001f3740\", \"urn:ngsi-ld:AirQualityObserved:Co2:sensor3\": \"urn:ngsi-ld:Device:chirpstack:0004a30b001bbf28\", \"urn:ngsi-ld:AirQualityObserved:Co2:sensor4\": \"urn:ngsi-ld:Device:chirpstack:2232330000888802\"}"
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  chirpstackdown:
    image: marcdespland/chirpstack-ngsiagent-down:1.0.0
    environment:
      - "ORION_API_URL=http://proxyld:8080"
      - "MQTT_URL=mqtt://mosquitto:1883"
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  covidsensorui:
    image: marcdespland/covidsensorui:latest
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"