version: "3.3"
services:
  chirpstackagent:
    image: marcdespland/chirpstack-ngsiagent:1.0.0
    environment:
      - ORION_API_URL=http://proxyld:8080
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  decoderagent:
    image: marcdespland/decoder-ngsiagent:1.1.0
    environment:
      - "ORION_API_URL=http://proxyld:8080"
      - "MQTT_URL=mqtt://mosquitto:1883"
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  chirpstackdown:
    image: marcdespland/chirpstack-ngsiagent-down:1.0.0
    environment:
      - "ORION_API_URL=http://proxyld:8080"
      - "MQTT_URL=mqtt://mosquitto:1883"
    depends_on:
      - proxyld
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  covidsensorui:
    image: marcdespland/covidsensorui:latest
    restart: always
    logging:
      options:
        max-size: "15m"
        max-file: "2"